name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3", "3.4", ruby-head, jruby-9.2, jruby-9.3, jruby-head]
      include:
        - ruby: "3.4"
          rubyopt: "--enable-frozen-string-literal --debug-frozen-string-literal"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
        bundler: latest
    - name: Run tests ${{ matrix.rubyopt }}
      run: bundle exec rake RUBYOPT="${{ matrix.rubyopt }}"
